In [6]:
#Класс нейрона
import random
import math
import numpy as np

class Neuron:
    # Массив весов
    inputW = []
    # Смещение
    t = 0.0
    
    '''
    Инициализация нейрона
    size - количество входов нейрона
    Начальные веса и смещение генерирются малыми 
    значениями, которые близки к нулю
    '''
    def __init__(self, size):
        self.inputW = []
        t = 0.0
        for i in range(size):
            a = random.random()/100.0
            self.inputW.append(a - 0.005)
        a = random.random()/100.0
        self.t = a - 0.005
    
    # Вычисление значения по входному образу
    def compute(self, inputS):
        S = - self.t
        for i in range(len(inputS)):
            S += self.inputW[i] * inputS[i]
        return self.__activation(S)
    
    # Выбор функции активации
    def __activation(self, x):
        return np.tanh(x)
    
    def __sigmoid(self, x):
        return 1 / (1 + math.exp(-x))
    
    def __stup(self, x):
        return -1 if x <= 0 else 1
    

In [7]:
#Класс сети
class Net:
    # Ошибка
    __err = 0
    # Коэфициент обучения
    __alpha = 0
    # Массив нейронов
    __neuron = []
    
    '''
    Инициализация сети
    sizeI - количество входов
    sizeN - количестно нейронов
    err - требуемая точность
    '''
    def __init__(self, sizeI, sizeN, err, alpha):
        self.__alpha = alpha
        self.__err = err
        self.__neuron = []
        for i in range(sizeN): 
            self.__neuron.append(Neuron(sizeI))
            
    def err(self):
        s = 0
        for i in range(len(self.__neuron)):
            for j in range(len(Data.inputL)):
                res = self.__neuron[i].compute(Data.inputL[j])
                if(i == j):
                    s += (1 - res) ** 2
                else:
                    s += (-1 - res) ** 2
        s /= (len(self.__neuron) * len(Data.inputL))   
        #s = s ** (1/2)
        #s /= 2
        print('Ошибка :', s)
        return True if s > (1 - self.__err) else False
            
    def learn(self):
        flag = True
        count = 0
        while(flag):
            count += 1
            flag = False
            for j in range(len(Data.inputL)):
                for i in range(len(self.__neuron)):
                
                    res = self.__neuron[i].compute(Data.inputL[j])
                    if(i == j):
                        self.modification(self.__neuron[i], Data.inputL[j], res, 1)
                    else:
                        self.modification(self.__neuron[i], Data.inputL[j], res, -1)
            flag = self.err()
        
        print('Количество эпох :', count)
        print('Веса')
        for i in range(len(self.__neuron)):
            print(np.array(self.__neuron[i].inputW))
        print('\n\n\n')
        

    def modification(self, neuron, x, y, d):
        for i in range(len(neuron.inputW)):
            neuron.inputW[i] = neuron.inputW[i] + x[i] * (d - y) * self.__alpha
        neuron.t = neuron.t + (d - y) * self.__alpha
    
    
    def test(self):
        
        for i in range(len(self.__neuron)):
            print('Проверка :', i)
            test = []
            for j in range(len(Data.inputT)):
                print(j, self.__neuron[i].compute(Data.inputT[j]).round(4))
                test.append([j, self.__neuron[i].compute(Data.inputT[j])])
            test = sorted(test, key=lambda x:x[1])
            print('Лучший результат :', test[-1])
            print('\n\n\n')
        

In [8]:
#Класс данных
class Data:
    
    inputL = [
        [0,0,1,1,0,0,1,0,0,1,0,1,0,0,1,0,1,1,1,1,0,1,0,0,1,0,1,0,0,1],
        [0,1,1,1,0,0,1,0,0,1,0,1,1,1,0,0,1,0,0,1,0,1,0,0,1,0,1,1,1,0],
        [0,0,1,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,1,0],
        [0,1,1,1,0,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,1,1,1,0],
        [0,1,1,1,1,0,1,0,0,0,0,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,1,1,1],
        [0,1,1,1,1,0,1,0,0,0,0,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0],
        [0,0,1,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,1,1,0,1,0,0,1,0,0,1,1,0],
        [0,1,0,0,1,0,1,0,0,1,0,1,1,1,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1],
        [0,1,1,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,1,0],
        [0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0,1,0,0,1,0,0,1,1,0],
    ]

    inputT = [
        [0,1,1,1,1, 0,1,0,0,1, 0,1,0,0,1, 0,1,1,1,1, 0,1,0,0,1, 0,1,0,0,1],
        [0,1,1,1,0, 0,1,0,0,1, 0,1,0,1,0, 0,1,0,0,1, 0,1,0,0,1, 0,1,1,1,0],
        [0,0,1,1,1, 0,1,0,0,1, 0,1,0,0,0, 0,1,0,0,0, 0,1,0,0,1, 0,0,1,1,1],
        [0,0,1,1,0, 0,1,0,0,1, 0,1,0,0,1, 0,1,0,0,1, 0,1,0,0,1, 0,1,1,1,0],
        [0,1,1,1,0, 0,1,0,0,0, 0,1,1,1,0, 0,1,0,0,0, 0,1,0,0,0, 0,1,1,1,0],
        [0,1,1,1,1, 0,0,0,0,0, 0,1,1,1,0, 0,1,0,0,0, 0,1,0,0,0, 0,1,0,0,0],
        [0,0,1,1,0, 0,1,0,0,1, 0,1,0,0,0, 0,1,0,1,1, 0,1,0,1,1, 0,0,1,1,1],
        [0,0,0,0,1, 0,1,0,0,1, 0,1,0,1,1, 0,1,0,0,1, 0,1,0,0,1, 0,1,0,0,1],
        [0,1,1,0,0, 0,0,1,0,0, 0,0,1,0,0, 0,0,1,0,0, 0,0,1,0,0, 0,1,1,0,0],
        [0,0,0,0,0, 0,0,0,0,1, 0,0,0,0,1, 0,0,0,0,1, 0,1,0,0,1, 0,0,1,1,1],
    ]

In [9]:
import numpy as np
for i in range(len(Data.inputL)):
    a = np.array(Data.inputL[i])
    a.shape = (6, 5)
    b = np.array(Data.inputT[i])
    b.shape = (6, 5)
    print(a, '\n')
    print(b, '\n\n\n')

[[0 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 1]
 [0 1 0 0 1]
 [0 1 0 0 1]] 

[[0 1 1 1 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 1]
 [0 1 0 0 1]
 [0 1 0 0 1]] 



[[0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 0]] 

[[0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 0]] 



[[0 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 0 1 1 0]] 

[[0 0 1 1 1]
 [0 1 0 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 0 1 1 1]] 



[[0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 0]] 

[[0 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 0]] 



[[0 1 1 1 1]
 [0 1 0 0 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 1 1 1]] 

[[0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 1 1 0]] 



[[0 1 1 1 1]
 [0 1 0 0 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]] 

[[0 1 1 1 1]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]] 



[[0 0 1 1 0]
 [0

In [10]:

web = Net(30, 10, 0.99, 0.1)
print("Обучение")
web.learn()
print("Test")
web.test()

Обучение
Ошибка : 0.26691028652386356
Ошибка : 0.19753166004890063
Ошибка : 0.15695288450904546
Ошибка : 0.12606793861603904
Ошибка : 0.09889851649981163
Ошибка : 0.07649061829890419
Ошибка : 0.05946514605962954
Ошибка : 0.04662433844851271
Ошибка : 0.036812209316684635
Ошибка : 0.029398015092436162
Ошибка : 0.023891420658708643
Ошибка : 0.019807995791777302
Ошибка : 0.016735493088410623
Ошибка : 0.0143727529748203
Ошибка : 0.012514632932245064
Ошибка : 0.011023187833137271
Ошибка : 0.00980447284429978
Количество эпох : 17
Веса
[ 0.00388307 -0.68405075 -0.05398415 -0.04940964 -0.4120267   0.00113147
 -0.13692978 -0.10012205 -0.00144757 -0.15889246  0.00108246 -0.133844
 -0.59847555 -0.49125486  0.36600386 -0.001474   -0.25611328  0.65231587
  0.59393135 -0.01012451  0.00195168 -0.25789777 -0.10708425  0.00236639
 -0.15075131 -0.00093219  0.07372318 -0.85875038 -0.85711594  0.54817921]
[-4.48152498e-03  8.64918325e-02 -5.50585202e-01 -5.55156803e-01
 -1.37569152e+00  4.54148349e-03 -4.3