In [5]:
#Класс нейрона
import random
import math
import numpy as np

class Neuron:
    # Массив весов
    inputW = []
    # Смещение
    t = 0.0
    
    '''
    Инициализация нейрона
    size - количество входов нейрона
    Начальные веса и смещение генерирются малыми 
    значениями, которые близки к нулю
    '''
    def __init__(self, size):
        self.inputW = []
        t = 0.0
        for i in range(size):
            a = random.random()/10.0
            self.inputW.append(a - 0.05)
        a = random.random()/10.0
        self.t = a - 0.05
    
    # Вычисление значения по входному образу
    def compute(self, inputS):
        S = - self.t
        for i in range(len(inputS)):
            S += self.inputW[i] * inputS[i]
        return self.__activation(S)
    
    # Выбор функции активации
    def __activation(self, x):
        return np.tanh(x)
    
    def __sigmoid(self, x):
        return 1 / (1 + math.exp(-x))
    
    def __stup(self, x):
        return -1 if x <= 0 else 1
 

In [6]:
#Класс сети
class Net:
    # Ошибка
    __err = 0
    # Массив нейронов
    __neuron = []
    
    '''
    Инициализация сети
    sizeI - количество входов
    sizeN - количестно нейронов
    err - требуемая точность
    '''
    def __init__(self, sizeI, sizeN, err):
        self.__err = err
        self.__neuron = []
        for i in range(sizeN): 
            self.__neuron.append(Neuron(sizeI))
            
    def learn(self):
        flag = True
        count = 0
        while(flag):
            count += 1
            flag = False
            for j in range(len(Data.inputL)):
                for i in range(len(self.__neuron)):
                
                    res = self.__neuron[i].compute(Data.inputL[j])
                    if(i == j): 
                        if (res < self.__err):
                            self.modification(self.__neuron[i], Data.inputL[j], 1)
                            flag = True
                    else:
                        if (res > -self.__err):
                            self.modification(self.__neuron[i], Data.inputL[j], -1)
                            flag = True
        print('Количество эпох :', count)
        print('Веса')
        for i in range(len(self.__neuron)):
            print(np.array(self.__neuron[i].inputW))
        print('\n\n\n')

    
    def modification(self, neuron, x, d):
        for i in range(len(neuron.inputW)):
            neuron.inputW[i] = neuron.inputW[i] + x[i] * d
        neuron.t = neuron.t - d 
        
    def test(self):
        
        for i in range(len(self.__neuron)):
            #print(self.__neuron[i].inputW)
            print('Проверка :', i)
            test = []
            for j in range(len(Data.inputT)):
                print(j, self.__neuron[i].compute(Data.inputT[j]).round(4))
                test.append([j, self.__neuron[i].compute(Data.inputT[j])])
            test = sorted(test, key=lambda x:x[1])
            #print(test)
            print('Лучший результат :', test[-1])
            print('\n\n\n')
        

In [7]:
#Класс данных
class Data:
    
    inputL = [
        [0,0,1,1,0,0,1,0,0,1,0,1,0,0,1,0,1,1,1,1,0,1,0,0,1,0,1,0,0,1],
        [0,1,1,1,0,0,1,0,0,1,0,1,1,1,0,0,1,0,0,1,0,1,0,0,1,0,1,1,1,0],
        [0,0,1,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,1,0],
        [0,1,1,1,0,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1,0,1,1,1,0],
        [0,1,1,1,1,0,1,0,0,0,0,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,1,1,1],
        [0,1,1,1,1,0,1,0,0,0,0,1,1,1,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0],
        [0,0,1,1,0,0,1,0,0,1,0,1,0,0,0,0,1,0,1,1,0,1,0,0,1,0,0,1,1,0],
        [0,1,0,0,1,0,1,0,0,1,0,1,1,1,1,0,1,0,0,1,0,1,0,0,1,0,1,0,0,1],
        [0,1,1,1,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,1,1,1,0],
        [0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,1,0,0,1,0,1,0,0,1,0,0,1,1,0],
    ]

    inputT = [
        [0,1,1,1,1, 0,1,0,0,1, 0,1,0,0,1, 0,1,1,1,1, 0,1,0,0,1, 0,1,0,0,1],
        [0,1,1,1,0, 0,1,0,0,1, 0,1,0,1,0, 0,1,0,0,1, 0,1,0,0,1, 0,1,1,1,0],
        [0,0,1,1,1, 0,1,0,0,1, 0,1,0,0,0, 0,1,0,0,0, 0,1,0,0,1, 0,0,1,1,1],
        [0,0,1,1,0, 0,1,0,0,1, 0,1,0,0,1, 0,1,0,0,1, 0,1,0,0,1, 0,1,1,1,0],
        [0,1,1,1,0, 0,1,0,0,0, 0,1,1,1,0, 0,1,0,0,0, 0,1,0,0,0, 0,1,1,1,0],
        [0,1,1,1,1, 0,0,0,0,0, 0,1,1,1,0, 0,1,0,0,0, 0,1,0,0,0, 0,1,0,0,0],
        [0,0,1,1,0, 0,1,0,0,1, 0,1,0,0,0, 0,1,0,1,1, 0,1,0,1,1, 0,0,1,1,1],
        [0,0,0,0,1, 0,1,0,0,1, 0,1,0,1,1, 0,1,0,0,1, 0,1,0,0,1, 0,1,0,0,1],
        [0,1,1,0,0, 0,0,1,0,0, 0,0,1,0,0, 0,0,1,0,0, 0,0,1,0,0, 0,1,1,0,0],
        [0,0,0,0,0, 0,0,0,0,1, 0,0,0,0,1, 0,0,0,0,1, 0,1,0,0,1, 0,0,1,1,1],
    ]

In [8]:
import numpy as np
for i in range(len(Data.inputL)):
    a = np.array(Data.inputL[i])
    a.shape = (6, 5)
    b = np.array(Data.inputT[i])
    b.shape = (6, 5)
    print(a, '\n')
    print(b, '\n\n\n')

[[0 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 1]
 [0 1 0 0 1]
 [0 1 0 0 1]] 

[[0 1 1 1 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 1]
 [0 1 0 0 1]
 [0 1 0 0 1]] 



[[0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 0]] 

[[0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 0]] 



[[0 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 0 1 1 0]] 

[[0 0 1 1 1]
 [0 1 0 0 1]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 1]
 [0 0 1 1 1]] 



[[0 1 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 0]] 

[[0 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 1 1 1 0]] 



[[0 1 1 1 1]
 [0 1 0 0 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 1 1 1]] 

[[0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 1 1 0]] 



[[0 1 1 1 1]
 [0 1 0 0 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]] 

[[0 1 1 1 1]
 [0 0 0 0 0]
 [0 1 1 1 0]
 [0 1 0 0 0]
 [0 1 0 0 0]
 [0 1 0 0 0]] 



[[0 0 1 1 0]
 [0

In [9]:

web = Net(30, 10, 0.95)
print("Обучение")
web.learn()
print("Test")
web.test()

Обучение
Количество эпох : 12
Веса
[ 2.63637976e-02 -3.04908173e+00 -6.10766828e-03  3.81808978e-02
 -9.68280492e-01 -1.53752314e-02 -1.03282468e+00 -1.12467034e-04
 -2.12899613e-02 -1.04466219e+00  2.56483177e-02 -1.02382320e+00
 -1.97858841e+00 -1.97536936e+00  1.97190310e+00 -3.93596071e-02
 -1.02460389e+00  4.02468288e+00  2.03868467e+00 -9.68748528e-01
  3.51151898e-02 -9.60549602e-01 -4.79844754e-03 -3.04666325e-02
 -1.04365582e+00 -1.50843963e-03  9.61082024e-01 -4.00695979e+00
 -3.99448584e+00  3.01040604e+00]
[ 3.07667717e-02  2.53811108e-03 -3.03390914e+00 -2.99000323e+00
 -5.03508465e+00 -4.24513715e-02 -1.97464170e+00 -1.03885824e+00
  2.32911117e-03  2.97231578e+00 -9.74433644e-03 -2.00110771e+00
  5.01839269e+00  5.98277108e+00 -6.04534384e+00  2.93094054e-02
 -1.96446797e+00 -1.97099897e+00 -1.00251171e+00  4.96756456e+00
 -4.71368477e-02 -1.97057353e+00 -9.84230778e-01 -1.66085361e-02
  2.95051547e+00 -3.12142218e-02 -9.69713486e-01 -2.75945071e-02
  4.74471214e-03 -3.9